version: "3.8"
services:
  reach-dossier:
    container_name: "reach-dossier"
    build: ..
    environment:
      - HTTP_REACH_DOSSIER_PORT=${HTTP_REACH_DOSSIER_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_REACH_DOSSIER_URL=jdbc:sqlserver://reach-database:1433;database=reach-dossier;
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
      - AZURE_TMP_STORAGE_CONNECTION_STRING=${AZURE_TMP_STORAGE_CONNECTION_STRING}
      - AZURE_TMP_STORAGE_CONTAINER_NAME=${AZURE_TMP_STORAGE_CONTAINER_NAME}
      - APPLICATION_INSIGHTS_IKEY=${APPLICATION_INSIGHTS_IKEY}
      - TEMP_DOSSIER_DAYS_TO_EXPIRE=1
      - JAVA_MX=256M
      - JAVA_MS=256M
    ports:
      - ${HTTP_REACH_DOSSIER_PORT}:${HTTP_REACH_DOSSIER_PORT}
